name: Deploy Comunidad Humm to HostGator Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to HostGator Server
    runs-on: ubuntu-latest

    steps:
      - name: 1. Checkout Código
        uses: actions/checkout@v4

      - name: 2. Sincronizar archivos al servidor vía RSYNC
        uses: easingthemes/ssh-deploy@v5.1.1
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "-avzr"
          SOURCE: "./"
          REMOTE_HOST: ${{ secrets.SSH_HOST }}
          REMOTE_USER: ${{ secrets.SSH_USER }}
          REMOTE_PORT: ${{ secrets.SSH_PORT }}
          TARGET: ${{ secrets.TARGET_DIR }}
          EXCLUDE: "/.git/, /.github/, /.DS_Store, /tmp/"
